services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.3
    command: ["start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASS}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  posture_api:
    build: ./services/posture_api
    container_name: posture_api
    environment:
      DATABASE_URL: mysql+pymysql://${SECURITY_DB_USER}:${SECURITY_DB_PASS}@security_db:3306/posture_db
      GLPI_API_URL: http://glpi/apirest.php
      GLPI_USER_TOKEN: ${GLPI_USER_TOKEN}
      GLPI_APP_TOKEN: ${GLPI_APP_TOKEN}
    ports:
      - "8010:8010"
    depends_on:
      - security_db
      - glpi
    restart: unless-stopped

  security_db:
    image: mariadb:10.11
    container_name: capstone_security_db
    environment:
      MYSQL_ROOT_PASSWORD: ${SECURITY_DB_ROOT_PASS}
      MYSQL_USER: ${SECURITY_DB_USER}
      MYSQL_PASSWORD: ${SECURITY_DB_PASS}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - security_data:/var/lib/mysql
    ports:
      - "${SECURITY_DB_PORT}:3306"
    restart: unless-stopped

  resource_api:
    build: ./services/resource_api
    container_name: resource_api
    environment:
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      KEYCLOAK_VALID_ISSUERS: ${KEYCLOAK_VALID_ISSUERS}
      KEYCLOAK_JWKS_URL: ${KEYCLOAK_JWKS_URL}
      AUDIT_DB_URL: mysql+pymysql://${SECURITY_DB_USER}:${SECURITY_DB_PASS}@security_db:3306/audit_log
      POSTURE_API_URL: http://posture_api:8010
    ports:
      - "8000:8020"
    volumes:
      - ./logs:/var/log/capstone
    depends_on:
      - security_db

  glpi_db:
    image: mariadb:10.11
    container_name: capstone_glpi_db
    environment:
      MYSQL_ROOT_PASSWORD: ${GLPI_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}
    volumes:
      - glpi_db_data:/var/lib/mysql
    restart: unless-stopped

  glpi:
    image: glpi/glpi:latest
    container_name: capstone_glpi
    environment:
      - TIMEZONE=America/New_York
      - GLPI_DB_HOST=glpi_db
      - GLPI_DB_NAME=${GLPI_DB_NAME}
      - GLPI_DB_USER=${GLPI_DB_USER}
      - GLPI_DB_PASSWORD=${GLPI_DB_PASSWORD}
    ports:
      - "${GLPI_PORT}:80"
    depends_on:
      - glpi_db
    restart: unless-stopped

  splunk:
    image: splunk/splunk:latest
    container_name: splunk_enterprise
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
    ports:
      - "8040:8000"
      - "8089:8089"
      - "9997:9997"
    volumes:
      - splunk_data:/opt/splunk/etc
      - splunk_var:/opt/splunk/var

  splunk_forwarder:
    build: ./splunk
    container_name: splunk_forwarder
    depends_on:
      - splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_FORWARD_SERVER=splunk:9997
    volumes:
      - ./logs:/var/log/capstone:ro

  alert_fwd:
    build: ./alert_fwd
    container_name: capstone_alert_fwd
    environment:
      - GLPI_URL=http://glpi
      - GLPI_APP_TOKEN=${GLPI_APP_TOKEN}
      - GLPI_USER_TOKEN=${GLPI_USER_TOKEN}
    ports:
      - "5050:5000"

volumes:
  security_data:
  glpi_db_data:
  keycloak_data:
  splunk_data:
  splunk_var:
